//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public int idFriendship { get; set; }
        public int idPlayerTwo { get; set; }
        public int FK_idPlayerOne { get; set; }
        public string state { get; set; }
    
        public virtual AccesAccount AccesAccount { get; set; }
    }
}
