//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leaderboard
    {
        public int wonMatches { get; set; }
        public int lostMatches { get; set; }
        public int drawMatches { get; set; }
        public int totalOfMatches { get; set; }
        public int FK_IdAccount { get; set; }
    
        public virtual AccessAccount AccessAccount { get; set; }
    }
}
